providers = ["node"]

[phases.install]
cmds = [
  "npm --prefix frontend install --include=dev",
  "npm --prefix backend install --omit=dev"
]

[phases.build]
cmds = ["npm --prefix frontend run build"]
